import Head from 'next/head';
import { useAsset } from '@/util/assetContext';
import Banner from '@/components/Banner';
import Chart from '@/components/Chart';
import Metrics from '@/components/Metrics';
import { Box } from '@chakra-ui/react';

export default function Home() {
  const { asset } = useAsset();
  return (
    <>
      <Head>
        <title>Asset Overview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hi {asset}</h1>
        <Banner />
        <Box display="flex" flexDir="row" mt={10}>
          <Chart />
          <Metrics />
        </Box>
      </main>
    </>
  );
}
