import Banner from '@/components/Banner';
import Chart from '@/components/Chart';
import Metrics from '@/components/Metrics';
import { Box } from '@chakra-ui/react';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Asset Overview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner />
        <Box display="flex" flexDir="row" mt={10}>
          <Chart />
          <Metrics />
        </Box>
      </main>
    </>
  );
}
