import Head from 'next/head';
import { useAsset } from '@/util/assetContext';

export default function Home() {
  const { asset } = useAsset();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hi {asset}</h1>
      </main>
    </>
  );
}
